version: "3.9"

services:

  vector-db:
    image: postgres:16
    container_name: llm-postgres-vector
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - llm_pgvector_data:/var/lib/postgresql/data
      - ./pgvector-init.sql:/docker-entrypoint-initdb.d/pgvector-init.sql:ro
    networks:
      - llm_private_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rag-engine:
    build: ./rag-engine
    container_name: llm-rag-engine
    restart: unless-stopped
    ports:
      - "${RAG_API_PORT:-5100}:5100"
    volumes:
      - ${RAG_DOC_DIR}:/app/rag_documents:ro

    networks:
      - llm_private_net
    depends_on:
      - vector-db
      - ollama-server
    environment:
      - RAG_DB_HOST=${RAG_DB_HOST}
      - RAG_DB_PORT=${RAG_DB_PORT}
      - RAG_DB_NAME=${RAG_DB_NAME}
      - RAG_DB_USER=${RAG_DB_USER}
      - RAG_DB_PASSWORD=${RAG_DB_PASSWORD}
      - RAG_OLLAMA_BASE_URL=http://ollama-server:11434

  ollama-server:
    image: ollama/ollama:latest
    container_name: llm-ollama
    restart: unless-stopped
    runtime: ${GPU_RUNTIME:-runc}
    ports:
      - "11434:11434"
    environment:
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - llm_ollama_models:/root/.ollama
    networks:
      - llm_private_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["serve"]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: llm-openwebui
    restart: unless-stopped
    ports:
      - "${WEBUI_PORT:-3000}:8080"
    volumes:
      - llm_openwebui_data:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama-server:11434
      - WEBUI_AUTH_DISABLED=${WEBUI_AUTH_DISABLED}
    networks:
      - llm_private_net
    depends_on:
      - ollama-server

networks:
  llm_private_net:
    driver: bridge

volumes:
  llm_pgvector_data:
  llm_ollama_models:
  llm_openwebui_data:


